trigger: none
pr: none

pool:
  name: NetCore1ESPool-Svc-Internal
  demands: ImageOverride -equals 1es-ubuntu-2004

resources:
  pipelines:
  - pipeline: dotnet-staging-pipeline-resource
    source: Stage-DotNet-Test

parameters:
- name: useSpecificPipelineRunIDs
  displayName: Use specific pipeline run IDs
  type: boolean
  default: false
- name: dotnetDotnetRunID
  displayName: Specific dotnet-dotnet run ID
  type: string
  default: '200XXXX'
- name: releaseBranchName
  displayName: Release branch name without the refs/heads prefix. For example, release/7.0.1xx or release/8.0.1xx-preview1
  type: string

variables:
- template: templates/variables/installer-pipelines.yml

jobs:
- job: SourceBuildPreRelease
  displayName: Source Build Pre-Release

  steps:
  - template: templates/steps/get-build-info.yml
    parameters:
      dotnetStagingPipelineResource: dotnet-staging-pipeline-resource
      getAssociatedPipelineRuns: true
      useSpecificPipelineRunIDs: ${{ parameters.useSpecificPipelineRunIDs }}
      dotnetDotnetRunID: ${{ parameters.dotnetDotnetRunID }}
      releaseBranchName: ${{ parameters.releaseBranchName }}
